# BEFORE: docker network create nginx-proxy
version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $HOME/ssl:/etc/nginx/certs

  registry:
     image: registry:2
     expose:
       - 80
     restart: always
     environment:
       VIRTUAL_HOST: registry.s1.joffreybvn.be
       VIRTUAL_PROTO: http
       VIRTUAL_PORT: 80
       CERT_NAME: joffreybvn.be
     container_name: registry

networks:
  default:
    external:
      name: nginx-proxy
